source "https://rubygems.org"

gem "rake"
gem "ruboty-slack"
gem "ruboty-alias"
gem "ruboty-cron"
gem "ruboty-google_image"
gem "ruboty-redis"
gem "ruboty-echo"
gem "ruboty-talk"
# gem "ruboty-ruby"
# gem "ruboty-train_delay"
